version: '3.1'

services:
  database:
    container_name: dsar-mongo-database
    image: mongo
    restart: always
    volumes:
      - dsar_mongo_data:/data/db
    ports:
      - '27017:27017'

volumes:
  dsar_mongo_data:
    driver: local
